spring:
  datasource:
    url: jdbc:h2:mem:ExchangeRateDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

error:
  documentation:
    baseUrl: http://localhost:8080/api/v1
server.id: server1
